const STANDART_RESOLUTION = '32';
const CANVAS_PIXEL_SIZE = 512;
const CANVAS_FRAMES_PIXEL_SIZE = 128;
const COLOR_GREEN = '#00ff00';
const COLOR_BLACK = '#000000';
const COLOR_WHITE = '#ffffff';


export {
  STANDART_RESOLUTION,
  CANVAS_PIXEL_SIZE,
  CANVAS_FRAMES_PIXEL_SIZE,
  COLOR_GREEN,
  COLOR_BLACK,
  COLOR_WHITE,
};
